### ISSUE TITLE
TypeInitializationException in .Net Core 2.1

### ISSUE THREAD

**Issue by MarcStan** [deniszykov/typeconvert#1]
Hey,

I know .Net Core 2.1 was just released today, but I'm already trying to upgrade some applications. :D

I'm actually using your commandline package which is how I noticed the issue first [described here](https://github.com/deniszykov/commandline/issues/6):

> var converted = TypeConvert.Convert(value, typeof(string));

The call above eventually results in this exception under .Net Core 2.1 no matter what type is converted (while everything works just fine with .Net Core 2.0):

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'TypeConversion`2' threw an exception.
  Source=TypeConvert
  StackTrace:
   at System.TypeConvert.Convert[FromType,ToType](FromType value, String format, IFormatProvider formatProvider) in C:\Projects\typeconvert\TypeConvert\TypeConvert.cs:line 528
   at ConsoleApp1.Program.Main(String[] args) in C:\Projects\typeconvert\ConsoleApp1\Program.cs:line 12

Inner Exception 1:
TypeInitializationException: The type initializer for 'ConvertibleType`1' threw an exception.

Inner Exception 2:
BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Edit:
Environment: Windows 10, x64
Tested by compiling in Any CPU, x86 and x64.

**Comment by deniszykov** [comment]
Found a problem. It is new ByRefLike types. They gives BadImageFormatException if you use them in generic types/method with inappropriate signature. Error message should be clearer, but I think this is unexpected case for runtime and error is kinda fatal level. 

Fixed in new release [2.1.1](https://www.nuget.org/packages/TypeConvert/2.1.1)
